<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="floating_base_1RDOF_2Link">
  <!-- =================================================================================== -->
  <!-- |    Author: Yeshasvi Tirupachuri                                                 | -->
  <!-- |    Date: 25 JULY 2016                                                           | -->
  <!-- |    Email: Yeshasvi.Tirupachuri@iit.it                                           | -->
  <!-- |    Institute: RBCS Department, Italian Institute of Technology, Genova          | -->
  <!-- |    Description: Xacro file for 2R Manipulator                                   | -->
  <!-- |    for URDF: rosrun xacro xacro model.xacro > model.urdf                        | -->
  <!-- |    for SDF: gz sdf -p model.urdf > model.sdf                                    | -->
  <!-- =================================================================================== -->


<!--XACRO: Axis Rotation - 180 Degree/ Pi Radians-->
<xacro:property name="angle" value="3.14"/>

<!--XACRO: Inertia Value-->
<xacro:property name="inertia" value="0.001"/>

<!--XACRO: Small Rectangle-->
<xacro:property name="length_small_box" value="0.05"/>
<xacro:property name="width_small_box" value="${length_small_box*2}"/>
<xacro:property name="height_small_box" value="${length_small_box/2}"/>

<!--XACRO: Small Cylinder-->
<xacro:property name="length_small_cylinder" value="${height_small_box}"/>
<xacro:property name="radius_small_cylinder" value="${length_small_box/2}"/>

<!--XACRO: First Link Rectangle-->
<xacro:property name="length_link1_box" value="0.05"/>
<xacro:property name="width_link1_box" value="0.2"/>
<xacro:property name="height_link1_box" value="0.05"/>

<!--XACRO: Second Link Rectangle-->
<xacro:property name="length_link2_box" value="0.05"/>
<xacro:property name="width_link2_box" value="0.2"/>
<xacro:property name="height_link2_box" value="0.05"/>

<!--XACRO: Link Masses-->
<xacro:property name="first_link_mass" value="1"/>
<xacro:property name="second_link_mass" value="1"/>

<!--XACRO: Link Inertia Value-->
<xacro:property name="first_link_inertia_xx" value="${inertia}"/>
<xacro:property name="first_link_inertia_yy" value="${inertia}"/>
<xacro:property name="first_link_inertia_zz" value="${inertia}"/>

<xacro:property name="second_link_inertia_xx" value="${inertia}"/>
<xacro:property name="second_link_inertia_yy" value="${inertia}"/>
<xacro:property name="second_link_inertia_zz" value="${inertia}"/>

<link name="world" />

<!--First Link-->
<link name="first_link">

  <inertial>
    <origin xyz="0 ${radius_small_cylinder*3/2+length_small_box*3/2+length_link1_box/2} 0" rpy="0 0 0"/>
    <mass value="${first_link_mass}" />
    <inertia ixx="${first_link_inertia_xx}" iyy="${first_link_inertia_yy}" izz="${first_link_inertia_zz}" ixy="0" ixz="0" iyz="0" />
  </inertial>

  <!--First Link Small Cylinder - Front -->
    <visual>
      <origin xyz="0 0 -0.0125" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
        <material name="white">
          <color rgba="1.0 1.0 1.0 1.0"/>
        </material>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 -0.01255" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
      </geometry>
    </collision>

    <!--First Link Small Box - Front -->
      <visual>
        <origin xyz="0 ${radius_small_cylinder*2} -0.01255" rpy="0 0 0"/>
        <geometry>
          <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
          <material name="white">
            <color rgba="1.0 1.0 1.0 1.0"/>
          </material>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 ${radius_small_cylinder*2} -0.0125" rpy="0 0 0"/>
        <geometry>
          <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
        </geometry>
      </collision>

      <!--First Link Box-->
        <visual>
          <origin xyz="0 ${radius_small_cylinder*6} 0" rpy="0 0 0"/>
          <geometry>
            <box size="${length_link1_box} ${width_link1_box} ${height_link1_box}"/>
            <material name="white">
              <color rgba="1.0 1.0 1.0 1.0"/>
            </material>
          </geometry>
        </visual>

        <collision>
          <origin xyz="0 ${radius_small_cylinder*6} 0" rpy="0 0 0"/>
          <geometry>
            <box size="${length_link1_box} ${width_link1_box} ${height_link1_box}"/>
          </geometry>
        </collision>

</link>

<!--Second Link-->
<link name="second_link">

  <inertial>
    <origin xyz="0 ${radius_small_cylinder*3/2+length_small_box*3/2+length_link2_box/2} 0" rpy="0 0 0"/>
    <mass value="${second_link_mass}" />
    <inertia ixx="${second_link_inertia_xx}" iyy="${second_link_inertia_yy}" izz="${second_link_inertia_zz}" ixy="0" ixz="0" iyz="0" />
  </inertial>

  <!--First Link Small Cylinder - Front -->
    <visual>
      <origin xyz="0 0 0.0125" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
        <material name="white">
          <color rgba="1.0 1.0 1.0 1.0"/>
        </material>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0.01255" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
      </geometry>
    </collision>

    <!--First Link Small Box - Front -->
      <visual>
        <origin xyz="0 ${radius_small_cylinder*2} 0.01255" rpy="0 0 0"/>
        <geometry>
          <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
          <material name="white">
            <color rgba="1.0 1.0 1.0 1.0"/>
          </material>
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 ${radius_small_cylinder*2} 0.0125" rpy="0 0 0"/>
        <geometry>
          <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
        </geometry>
      </collision>

      <!--First Link Box-->
        <visual>
          <origin xyz="0 ${radius_small_cylinder*6} 0" rpy="0 0 0"/>
          <geometry>
            <box size="${length_link2_box} ${width_link2_box} ${height_link2_box}"/>
            <material name="white">
              <color rgba="1.0 1.0 1.0 1.0"/>
            </material>
          </geometry>
        </visual>

        <collision>
          <origin xyz="0 ${radius_small_cylinder*6} 0" rpy="0 0 0"/>
          <geometry>
            <box size="${length_link2_box} ${width_link2_box} ${height_link2_box}"/>
          </geometry>
        </collision>
</link>

<!--Joints-->
<joint name="anchor" type="fixed">
  <parent link="world"/>
  <child link="first_link"/>
  <origin xyz="0 0 0.55" rpy="0 0 0"/>
</joint>

<joint name="first_joint" type="revolute">
  <parent link="first_link"/>
  <child link="second_link"/>
  <origin xyz="0 0 0" rpy="0 0 ${angle/2.5}"/>
  <axis xyz="0 0 1" />
  <calibration rising="1"/>
  <dynamic damping="0.0" friction="0.0"/>
  <limit effort="30" lower="0" upper="${angle/2}" velocity="1.0"/>
  <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-1.5" soft_upper_limit="1.5"/>
</joint>


</robot>
