<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="2r_manipulator_scaled_down">
  <!-- =================================================================================== -->
  <!-- |    Author: Yeshasvi Tirupachuri                                                 | -->
  <!-- |    Date: 22 JULY 2016                                                           | -->
  <!-- |    Email: Yeshasvi.Tirupachuri@iit.it                                           | -->
  <!-- |    Institute: RBCS Department, Italian Institute of Technology, Genova          | -->
  <!-- |    Description: Xacro file for 2R Manipulator                                   | -->
  <!-- |    for URDF: rosrun xacro xacro model.xacro > model.urdf                        | -->
  <!-- |    for SDF: gz sdf -p model.urdf > model.sdf                                    | -->
  <!-- =================================================================================== -->


<!--XACRO: Axis Rotation - 180 Degree/ Pi Radians-->
<xacro:property name="angle" value="3.14"/>

<!--XACRO: Small Rectangle-->
<xacro:property name="length_small_box" value="0.05"/>
<xacro:property name="width_small_box" value="${length_small_box*2}"/>
<xacro:property name="height_small_box" value="${length_small_box/2}"/>

<!--XACRO: Small Cylinder-->
<xacro:property name="length_small_cylinder" value="${height_small_box}"/>
<xacro:property name="radius_small_cylinder" value="${length_small_box/2}"/>

<!--XACRO: Base Rectangle-->
<xacro:property name="length_base_box" value="0.3"/>
<xacro:property name="width_base_box" value="0.05"/>
<xacro:property name="height_base_box" value="0.05"/>

<!--XACRO: First Link Rectangle-->
<xacro:property name="length_link1_box" value="0.05"/>
<xacro:property name="width_link1_box" value="0.2"/>
<xacro:property name="height_link1_box" value="0.05"/>

<!--XACRO: Second Link Rectangle-->
<xacro:property name="length_link2_box" value="0.05"/>
<xacro:property name="width_link2_box" value="0.2"/>
<xacro:property name="height_link2_box" value="0.05"/>

<!--XACRO: Handle Link Cylinder-->
<xacro:property name="length_handle_cylinder" value="${height_small_box*4}"/>
<xacro:property name="radius_handle_cylinder" value="${length_small_box/4}"/>

<!--XACRO: Link Masses-->
<xacro:property name="base_link_mass" value="1"/>
<xacro:property name="first_link_mass" value="1"/>
<xacro:property name="second_link_mass" value="1"/>
<xacro:property name="handle_link_mass" value="1"/>

<!--XACRO: Link Inertia Value-->
<xacro:property name="base_link_inertia_xx" value="1"/>
<xacro:property name="base_link_inertia_yy" value="1"/>
<xacro:property name="base_link_inertia_zz" value="1"/>

<xacro:property name="first_link_inertia_xx" value="1"/>
<xacro:property name="first_link_inertia_yy" value="1"/>
<xacro:property name="first_link_inertia_zz" value="1"/>

<xacro:property name="second_link_inertia_xx" value="1"/>
<xacro:property name="second_link_inertia_yy" value="1"/>
<xacro:property name="second_link_inertia_zz" value="1"/>


<xacro:property name="handle_link_inertia_xx" value="1"/>
<xacro:property name="handle_link_inertia_yy" value="1"/>
<xacro:property name="handle_link_inertia_zz" value="1"/>



<link name="world" />


<!--Base Link is at the Origin-->
<link name="base_link">

  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="${base_link_mass}" />
    <inertia ixx="${base_link_inertia_xx}" iyy="${base_link_inertia_yy}" izz="${base_link_inertia_zz}" ixy="0" ixz="0" iyz="0" />
  </inertial>

<!--Base Link Box-->
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${length_base_box} ${width_base_box} ${height_base_box}"/>
    </geometry>
    <material name="white">
      <color rgba="1.0 1.0 1.0 1.0"/>
    </material>
  </visual>

  <collision>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <box size="${length_base_box} ${width_base_box} ${height_base_box}"/>
    </geometry>
  </collision>

<!--Base Link Small Box-->
  <visual>
    <origin xyz="0 ${width_base_box/2} -${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
    </geometry>
    <material name="white">
      <color rgba="1.0 1.0 1.0 1.0"/>
    </material>
  </visual>

  <collision>
    <origin xyz="0 ${width_base_box/2} -${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
    </geometry>
  </collision>

<!--Base Link Small Cylinder-->
  <visual>
    <origin xyz="0 ${width_small_box*(3/4)} -${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
    </geometry>
    <material name="white">
      <color rgba="1.0 1.0 1.0 1.0"/>
    </material>
  </visual>

  <collision>
    <origin xyz="0 ${width_small_box*(3/4)} -${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
    </geometry>
  </collision>

</link>

<!--First Link-->
<link name="first_link">

  <inertial>
    <origin xyz="0 ${radius_small_cylinder*3/2+length_small_box*3/2+length_link1_box/2} 0" rpy="0 0 0"/>
    <mass value="${first_link_mass}" />
    <inertia ixx="${first_link_inertia_xx}" iyy="${first_link_inertia_yy}" izz="${first_link_inertia_zz}" ixy="0" ixz="0" iyz="0" />
  </inertial>

<!--First Link Small Cylinder - Front -->
  <visual>
    <origin xyz="0 0 ${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 0 ${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
    </geometry>
  </collision>

<!--First Link Small Box - Front -->
  <visual>
    <origin xyz="0 ${radius_small_cylinder*2} ${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 ${radius_small_cylinder*2} ${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
    </geometry>
  </collision>

<!--First Link Box-->
  <visual>
    <origin xyz="0 ${radius_small_cylinder*6} 0" rpy="0 0 0"/>
    <geometry>
      <box size="${length_link1_box} ${width_link1_box} ${height_link1_box}"/>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 ${radius_small_cylinder*6} 0" rpy="0 0 0"/>
    <geometry>
      <box size="${length_link1_box} ${width_link1_box} ${height_link1_box}"/>
    </geometry>
  </collision>

<!--First Link Small Box - Back -->
  <visual>
    <origin xyz="0 ${radius_small_cylinder*2+width_link1_box} -${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 ${radius_small_cylinder*2+width_link1_box} -${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
    </geometry>
  </collision>

<!--First Link Small Cylinder - Back -->
  <visual>
    <origin xyz="0 ${radius_small_cylinder*4+width_link1_box} -${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 ${radius_small_cylinder*4+width_link1_box} -${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
    </geometry>
  </collision>

</link>

<!--Second Link -->
<link name="second_link">

  <inertial>
    <origin xyz="0 ${radius_small_cylinder*3/2+length_small_box*3/2+length_link1_box/2} 0" rpy="0 0 0"/>
    <mass value="${second_link_mass}" />
    <inertia ixx="${second_link_inertia_xx}" iyy="${second_link_inertia_yy}" izz="${second_link_inertia_zz}" ixy="0" ixz="0" iyz="0" />
  </inertial>

<!--Second Link Small Cylinder - Front -->
  <visual>
    <origin xyz="0 0 ${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 0 ${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
    </geometry>
  </collision>

<!--Second Link Small Box - Front -->
  <visual>
    <origin xyz="0 ${radius_small_cylinder*2} ${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 ${radius_small_cylinder*2} ${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
    </geometry>
  </collision>

<!--Second Link Box-->
  <visual>
    <origin xyz="0 ${radius_small_cylinder*6} 0" rpy="0 0 0"/>
    <geometry>
      <box size="${length_link2_box} ${width_link2_box} ${height_link2_box}"/>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 ${radius_small_cylinder*6} 0" rpy="0 0 0"/>
    <geometry>
      <box size="${length_link2_box} ${width_link2_box} ${height_link2_box}"/>
    </geometry>
  </collision>

<!--Second Link Small Box - Back -->
  <visual>
    <origin xyz="0 ${radius_small_cylinder*2+width_link2_box} -${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 ${radius_small_cylinder*2+width_link2_box} -${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <box size="${length_small_box} ${width_small_box} ${height_small_box}"/>
    </geometry>
  </collision>

<!--Second Link Small Cylinder - Back -->
  <visual>
    <origin xyz="0 ${radius_small_cylinder*4+width_link2_box} -${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 ${radius_small_cylinder*4+width_link2_box} -${height_base_box/4}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${length_small_cylinder}" radius="${radius_small_cylinder}"/>
    </geometry>
  </collision>

</link>

<!--Handle Link-->
<link name="handle_link">

  <inertial>
    <origin xyz="0 0 ${height_base_box/4}" rpy="0 0 0"/>
    <mass value="${handle_link_mass}"/>
    <inertia ixx="${handle_link_inertia_xx}" iyy="${handle_link_inertia_yy}" izz="${handle_link_inertia_zz}" ixy="0" ixz="0" iyz="0" />
  </inertial>

  <visual>
    <origin xyz="0 0 ${height_base_box/2}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${length_handle_cylinder}" radius="${radius_handle_cylinder}"/>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </geometry>
  </visual>

  <collision>
    <origin xyz="0 0 ${height_base_box/2}" rpy="0 0 0"/>
    <geometry>
      <cylinder length="${length_handle_cylinder}" radius="${radius_handle_cylinder}"/>
    </geometry>
  </collision>

</link>

<!--Joints-->
<joint name="anchor" type="fixed">
  <parent link="world"/>
  <child link="base_link"/>
  <origin xyz="0 0 0.55" rpy="0 0 0" />
  <axis xyz="0 0 0" />
</joint>

<joint name="first_joint" type="revolute">
  <parent link="base_link"/>
  <child link="first_link"/>
  <origin xyz="0 ${width_small_box*(3/4)} 0" rpy="0 0 ${angle/8}" />
  <axis xyz="0 0 1" />
  <calibration rising="1"/>
  <dynamic damping="0.0" friction="0.0"/>
  <limit effort="30" lower="-${angle/4}" upper="0" velocity="1.0"/>
  <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-1.5" soft_upper_limit="1.5"/>
</joint>

<joint name="second_joint" type="revolute">
  <parent link="first_link"/>
  <child link="second_link"/>
  <origin xyz="0 ${width_small_box+width_link1_box} 0" rpy="0 0 -${angle/8}" />
  <axis xyz="0 0 1" />
  <calibration rising="1"/>
  <dynamic damping="0.0" friction="0.0"/>
  <limit effort="30" lower="-${angle/8}" upper="${angle/8}" velocity="1.0"/>
  <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-1.5" soft_upper_limit="1.5"/>
</joint>

<joint name="handle_joint" type="revolute">
  <parent link="second_link"/>
  <child link="handle_link"/>
  <origin xyz="0 ${width_small_box+width_link2_box} 0" rpy="0 0 0" />
  <axis xyz="0 0 1" />
  <calibration rising="1"/>
  <dynamic damping="0.0" friction="0.0"/>
  <limit effort="30" lower="-${angle}" upper="${angle}" velocity="1.0"/>
  <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-1.5" soft_upper_limit="1.5"/>

  <!--sensor name='handle_ft' type='force_torque'>
    <always_on>1</always_on>
    <update_rate>100</update_rate>
    <pose>0 0 0 0 0 0</pose>
    <plugin name='forcetorque' filename='libgazebo_yarp_forcetorque.so'>
      <yarpConfigurationFile>model://2r_manipulator_scaled_down/conf/gazebo_forcetorque.ini</yarpConfigurationFile>
    </plugin>
  </sensor-->

</joint>

<!--Gazebo Yarp Plugin-->
<!--plugin name="controlboard" filename="libgazebo_yarp_controlboard.so">
  <yarpConfigurationFile>model://2r_manipulator_scaled_down/conf/gazebo_controlboard.ini</yarpConfigurationFile>
  <initialConfiguration>0.0 0.0</initialConfiguration>
</plugin-->

</robot>
